import "react-toastify/dist/ReactToastify.css";
import "@/style/global.scss";

import { AuthProvider } from "@/app/provider";
import { ToastContainer } from "react-toastify";

import { Plus_Jakarta_Sans } from "next/font/google";
const plus_jakarta_sans = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={plus_jakarta_sans.className}>
        <AuthProvider>
          {children}
          <ToastContainer
            position="bottom-right"
            theme="dark"
            autoClose={1500}
          />
        </AuthProvider>
      </body>
    </html>
  );
}
